### ISSUE TITLE
Design the landing page

### ISSUE THREAD

**Issue by Showdowncode** [tiller-vgs/Timeplan#13]
# Task Description
- Add a simple structure to Class Schedule Website to add information on. CSS and design of landing page.
- Information on what will be added is down below under Subtasks.

# Linked User Story
- #1 

# Subtasks
- [ ] Create the page
- [ ] Add title
- [ ] Add structure with days
- [ ] Add time
- [ ] Add border
- [ ] Change color of the page
